/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_ROO_CONTROL_QUANTITY_PB_H_INCLUDED
#define PB_ROO_CONTROL_QUANTITY_PB_H_INCLUDED

/* Enum definitions */
typedef enum _roo_control_Quantity {
    roo_control_Quantity_kUnspecified = 0,
    /* Fundamental. */
    roo_control_Quantity_kElapsedTime = 1, /* [seconds]. */
    roo_control_Quantity_kMass = 2, /* [kilograms]. */
    roo_control_Quantity_kTemperature = 3, /* [deg C]. */
    roo_control_Quantity_kFrequency = 4, /* [Hz]. */
    roo_control_Quantity_kLength = 5, /* [m]. */
    roo_control_Quantity_kAngle = 6, /* [rad]. */
    /* Displacement. */
    roo_control_Quantity_kDistance = 10, /* [m]. */
    roo_control_Quantity_kVelocity = 11, /* [m/s]. */
    roo_control_Quantity_kAcceleration = 12, /* [m/s^2]. */
    roo_control_Quantity_kJerk = 13, /* [m/s^3]. */
    /* Force and energy. */
    roo_control_Quantity_kForce = 20, /* [N]. */
    roo_control_Quantity_kPressure = 21, /* [Pa]. */
    roo_control_Quantity_kEnergy = 22, /* [J]. */
    roo_control_Quantity_kPower = 23, /* [W]. */
    /* Spatial. */
    roo_control_Quantity_kArea = 30, /* [m^2]. */
    roo_control_Quantity_kVolume = 31, /* [m^3]. */
    /* Liquids. */
    roo_control_Quantity_kLiquidVolume = 40, /* [liter]. */
    roo_control_Quantity_kLiquidFlow = 41, /* [liter/min]. */
    /* Thermodynamics. */
    roo_control_Quantity_kHeat = 50, /* [J]. */
    /* Magnetism. */
    roo_control_Quantity_kMagneticFlux = 60, /* [We]. */
    /* Electricity. */
    roo_control_Quantity_kElectricCharge = 70, /* [C]. */
    roo_control_Quantity_kElectricCurrent = 71, /* [A]. */
    roo_control_Quantity_kVoltage = 72, /* [V]. */
    roo_control_Quantity_kResistance = 73, /* [Ohm]. */
    roo_control_Quantity_kImpedance = 74, /* [Ohm]. */
    roo_control_Quantity_kCapacitance = 75, /* [F]. */
    roo_control_Quantity_kInductance = 76, /* [T]. */
    /* Light. */
    roo_control_Quantity_kLuminousIntensity = 90, /* [lumen]. */
    roo_control_Quantity_kColorHue = 95, /* [0-360). */
    roo_control_Quantity_kColorSaturation = 96, /* [0-1]. */
    roo_control_Quantity_kColorBrightness = 97, /* [0-1]. */
    /* Geolocation. */
    roo_control_Quantity_kLatitude = 110, /* [-90-90] (North is positive). */
    roo_control_Quantity_kLongitude = 111, /* [-180-180] (East is positive). */
    roo_control_Quantity_kAltitude = 112, /* [m]. */
    /* Environmental. */
    roo_control_Quantity_kAirHumidity = 130 /* [%]. */
} roo_control_Quantity;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _roo_control_Quantity_MIN roo_control_Quantity_kUnspecified
#define _roo_control_Quantity_MAX roo_control_Quantity_kAirHumidity
#define _roo_control_Quantity_ARRAYSIZE ((roo_control_Quantity)(roo_control_Quantity_kAirHumidity+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
