/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "transceivers.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(roo_control_TransceiverDescriptor, roo_control_TransceiverDescriptor, 2)


PB_BIND(roo_control_TransceiverDescriptor_Sensor, roo_control_TransceiverDescriptor_Sensor, AUTO)


PB_BIND(roo_control_TransceiverDescriptor_Actuator, roo_control_TransceiverDescriptor_Actuator, AUTO)





